root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/auth ./cmd/auth"
  bin = "tmp/auth"
  full_bin = "APP_ENV=dev APP_NAME=auth ./tmp/auth"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "frontend"]
  exclude_file = ["go.sum"]
  follow_symlink = true
  dir = "cmd/auth"
  poll = true
  poll_interval = 500

[log]
  level = "debug"
  color = true
  time = true