version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./:/cmd
    depends_on:
      - redis
      - db
      - pdadmin
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: /bin/sh -c "redis-server --requirepass $REDIS_PASSWORD"
    env_file:
      - .env
  pdadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PDADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PDADMIN_DEFAULT_PASSWORD}
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  postgres-db:
  redis_data: